// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ass!!!","status":true,"description":"1.0.2 Fixes MV's framerate dependent timestepping. Makes the gamespeed the same regardless of framerate.","parameters":{}}
];
